Update toaststat

diff --git a/toaststat b/toaststat
--- a/toaststat
+++ b/toaststat
@@ -9,10 +9,10 @@
 #
 #  Warning: This script is not bullet-proof, use at your own risk.
 #
-#  Failure: Re-run
+#  Failure: Email the qmailtoaster-list with the error
 #
 #  Updates:
-#  
+#
 TAB="$(printf '\t')"
 GREEN=$(tput setaf 2)
 RED=$(tput setaf 1)
@@ -42,20 +42,22 @@ fi
 NAMED=
 for ns in djbdns named pdns-recursor
 do
-    [[ "`systemctl status $ns`" == *"Loaded"* ]] && NAMED=$ns
+   systemctl status $ns &> /dev/null
+   [ "$?" = "0" ] && NAMED=$ns
 done
 
+VSFTPD=
+cat /etc/vsftpd/vsftpd.conf | grep listen=NO &> /dev/null
+[ "$?" != "0" ] && VSFTPD=vsftpd
+
+
 SRV="systemd service"
+STAT=
+COLOR=
 # Toaster server service status
-sv=($CLAMD $CLAMS clamav-freshclam spamd dovecot mariadb httpd $NAMED vsftpd network acpid atd autofs crond ntpd smartd sshd irqbalance)
-for idx in ${!sv[*]}
+for sv in $CLAMD $CLAMS clamav-freshclam spamd dovecot mariadb httpd $NAMED ntpd sshd network crond $VSFTPD acpid atd autofs smartd irqbalance
 do
-   temp=${sv[$idx]}
-   systemctl status $temp > /dev/null 2>&1
-   ret0=$?
-   if [ "$ret0" = 0 ]; then
-       printf "%s %25.25s %s %s %s %s %s %s\n" "$SRV:" "$temp:" "${TAB}" "[" "$GREEN" "OK" "$NORMAL" "]"
-   else
-       printf "%s %25.25s %s %s %s %s %s %s\n" "$SRV:" "$temp:" "${TAB}" "[" "$RED" "FAILED" "$NORMAL" "]"
-    fi
+   systemctl status $sv &> /dev/null
+   [ "$?" = "0" ] && COLOR=$GREEN STAT=OK || COLOR=$RED STAT=FAILED
+   printf "%s %25.25s %s %s %s %s %s %s\n" "$SRV:" "$sv:" "${TAB}" "[" "$COLOR" "$STAT" "$NORMAL" "]"
 done
